name: build
on: push
jobs:
  # psycopg-ubuntu:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: sudo service postgresql start
  #     - run: sudo -u postgres createuser runner -s
  #     - run: createdb repro
  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: 3.12
  #     - run: pip install "psycopg[binary]"
  #     - run: python3 repro.py
  psycopg-mac:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - run: brew install postgresql
      - run: brew services start postgresql
      - run: createdb repro
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: pip install "psycopg[c]==3.0.10"
      - run: python3 repro.py
  # pg-mac:
  #   runs-on: macos-13
  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: brew install postgresql
  #     - run: brew services start postgresql
  #     - run: createdb repro
  #     - uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 3.3
  #     - run: gem install pg
  #     - run: ruby repro.rb
